### PR TITLE
Added instructions for to boot File System from SD Card

### PR DESCRIPTION
**Pull request by dbharbin**

### CODE REVIEW

**Comment by ndechesne** [comment]
Thanks! I will review next week!

**Comment by dbharbin** [comment]
Sounds good Nico.  We went ahead and merged it after a walkthru on HO.  Can fine tune after your review next week if needed.  Seems pretty clean.  A nice enhancement!

**Comment by ndechesne** [comment]
ah, ok. I have some comments:

* somehow it should be explained/clear that we only provide the 'developer' image for the SD method, not the full desktop. 
* DB410c should be Dragonboard 410c
* EMMC -> eMMC
* mounting a file system in /dev/xxx is a bad recommendation. e.g. 
sudo mount /dev/mmcblk0p10 /dev/internalemmc
Please change /dev/internalemmc with something else, maybe /mnt ..
* Users have been asking a few times how to 'dump' the emmc content entirely. I have given the recommendation to boot from SD to do that, since copying from emmc while booting from emmc is error prone. It might be a good idea to explain how to do that , in your hints section!

otherwise, thanks for doing this patch. really appreciated.

**Comment by dbharbin** [comment]
Good inputs thanks.  Will discuss updating with Robert.
Don

**Pull request merged**
