### PR TITLE
Update getting started for Ultra96v2

### PR DESCRIPTION
**Pull request by anielsen001**
The current getting started documentation for the Ultra96v2 is not correct. I updated it for the v2 board revision (new LED arrangement) and the current distributed package (blank SD card). This should address #855  that I reported.

Note that I squashed some commits and force pushed them to my repo, but github seems to be behind as I write this. Hopefully it will catch up before you see it.

### CODE REVIEW

**Comment by ric96** [comment]
@kylekirkby are your commits part of this pr as well, they seemed off-topic for this pr?

**Comment by kylekirkby** [comment]
> @kylekirkby are your commits part of this pr as well, they seemed off-topic for this pr?

I've not added any commits to this PR. Maybe @anielsen001 needs to pull in the latest commits ?

**Comment by ric96** [comment]
@anielsen001 can you please rebase your commits properly, you seem to have pulled in some extra ones.

**Comment by anielsen001** [comment]
sorry for the delay. I'll look at it.

**Comment by anielsen001** [comment]
I replaced this PR with #865, after fixing the history, so close this one.

**Pull request closed without merging**
