### PR TITLE
dragonboard: 410c: build: Add kernel build documentation

### PR DESCRIPTION
**Pull request by loicpoulain**
1. Install toolchain for cross-compiling
2. Retrieve kernel source
3. Build kernel/dtb/modules
4. Generate and flash boot image
5. Install modules

### CODE REVIEW

**Comment by ndechesne** [comment]
i think we have this information (or a large part of it) already in other places. is there a specific reason why we have a new page now? and if we do that, then I think we should remove from other places and link to here.

**Comment by loicpoulain** [comment]
@ndechesne, no reason to have a new page, but actually I didn't find the documentation covering kernel build for 410c. But maybe I didn't look at the right place.

**Comment by ndechesne** [comment]
I have to say that this has become such a mess ;)

i found at least this link
https://github.com/96boards/documentation/wiki/Dragonboard-Boot-Image

we have that for DB820c
https://git.linaro.org/landing-teams/working/qualcomm/lt-docs.git/tree/debian/boards/dragonboard410c/README.textile.in#n103

Then we also have instructions in the release notes, e.g.

https://git.linaro.org/landing-teams/working/qualcomm/lt-docs.git/tree/debian/boards/dragonboard410c/README.textile.in#n103

I am not against cleanup.. just want to make we don't duplicate more. 
The one in the release notes must stay there, since they are 'static' and correspond to a specific release. the one of the wiki/doc should be updated whenever needed.

**Comment by sdrobertw** [comment]
@ndechesne is right, this is still a big mess; however, we should hope to one day consolidate everything into this documentation repo in an organized fashion. Whether we are linking to, transferring from, or replacing, we need to do our best to reduce copies, sometimes easier said than done. 

@loicpoulain As @ndechesne said, we should do our best to remove any repeated information (or forward) once docs are merged into this repo. If it is a wiki page, just edit it down and replace with a link to forward here. git.linaro.org materials not easy to find (no where near public facing) and should probably be linked to from this repo... The landing team docs are also rendered onto the builds.96boards.org pages, but considering these will soon be transitioned into releases.linaro and snapshots.linaro, we will also need to have a transition plan...

🌊

**Comment by sdrobertw** [comment]
@ndechesne I would like to merge this PR, any objections? We will work on consolidation and forwarding once this page is live.

Thanks

**Pull request merged**
