### PR TITLE
README: Gratuitous change to provoke a link check

### PR DESCRIPTION
**Pull request by daniel-thompson**
Signed-off-by: Daniel Thompson <daniel.thompson@linaro.org>

### CODE REVIEW

**Comment by daniel-thompson** [comment]
@pcolmer @kylekirkby 
The CI checks appear to have failed because bamboo can't find jeykll binary anymore...

**Comment by daniel-thompson** [comment]
(I triggered a link check to make sure all the redirects from builds.96boards.org are pointing to the right thing)

**Comment by pcolmer** [comment]
@daniel-thompson we're having some problems with the build process for 96Boards at the moment. Your patience is appreciated :)

**Comment by daniel-thompson** [comment]
No worries... you'll ping when this is ok for resubmit? (actually, if you're doing some test runs all I care about is that there are no link errors during the test run).

**Comment by pcolmer** [comment]
Yes, I'll let you know when things are back in a working state :).

**Comment by pcolmer** [comment]
@daniel-thompson just to let you know that we've fixed the root cause of what was preventing the builds from completing. The reason your build didn't work is because @kylekirkby had reverted back to the old theme and that would have required configuration changes on Bamboo.

Kyle is now putting the new theme onto the develop branch so hopefully things will start moving forwards again :).

**Pull request closed without merging**
