### PR TITLE
Add OE guide for HiKey960

### PR DESCRIPTION
**Pull request by Mani-Sadhasivam**
This PR adds OpenEmbedded guide for Hikey960

Fixes: #189 

Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>

### CODE REVIEW

**Comment by Mani-Sadhasivam** [comment]
@sdrobertw @ric96 We might want to rework the OE guide for HiKey family later.

**Comment by Mani-Sadhasivam** [comment]
Not sure why the link test failed, on my side the blog link works...

**Comment by ric96** [comment]
@Mani-Sadhasivam just make a minor change, amend the commit and push. Should start the link checker again.

**Comment by sdrobertw** [comment]
@Mani-Sadhasivam @ric96 has that linked been fixed? It doesnt seem to be causing problems in any other PR's

**Comment by sdrobertw** [comment]
@Mani-Sadhasivam can I merge this, or are we waiting on someone else's approvals?

**Comment by Mani-Sadhasivam** [comment]
@sdrobertw You can merge this PR!

**Pull request merged**
