### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pedrombmachado**
fixed a typo

### CODE REVIEW

**Comment by pedrombmachado** [comment]
Hi @sgermanserrano ,
   The link is still broken. Try to open any of those links.

**Comment by sgermanserrano** [comment]
@pedrombmachado can you add here the website where you are facing the issue?

**Comment by pedrombmachado** [comment]
image
image

**Comment by pcolmer** [comment]
> The Link doesnt work in the Github UI but does on the Website, i assume this is due to the way the 96Boards Website is structured.

Correct.

The 96Boards website is built from two git repositories - website and documentation. As a result, links in the documentation repo will not work from the GitHub web interface.

Closing this PR.

**Pull request closed without merging**
