### PR TITLE
consumer: guides: OE: Switch to sumo version

### PR DESCRIPTION
**Pull request by Mani-Sadhasivam**
For OE, since we support sumo in our oe-rpb-manifest it makes sense to
switch to sumo which is also the latest stable version of OpenEmbedded.

Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>

### CODE REVIEW

**Comment by Mani-Sadhasivam** [comment]
Waiting for @ric96 to test it!

**Comment by sdrobertw** [comment]
@Mani-Sadhasivam was this tested? Can I merge now? I think I recall you saying something in a sync about this already being tested.

Thanks,

**Comment by Mani-Sadhasivam** [comment]
@sdrobertw Yes, you can merge this. One user reported a warning while building but that is not a blocker anyway.

**Comment by sdrobertw** [comment]
Done, thanks @Mani-Sadhasivam

**Pull request merged**
