### PR TITLE
DB410c: Update camera doc for release 18.01

### PR DESCRIPTION
**Pull request by todortomov**
Signed-off-by: Todor Tomov <todor.tomov@linaro.org>

### CODE REVIEW

**Comment by sdrobertw** [comment]
@ric96 @Mani-Sadhasivam Who originally wrote this guide?

**Comment by ndechesne** [comment]
The QC LT. Well Todor. I will have a look and merge.

Le ven. 2 févr. 2018 à 20:01, Robert Wolff <notifications@github.com> a
écrit :

**Comment by sdrobertw** [comment]
Thanks @ndechesne! Notice the new blocking system in place :) to ensure cross-checking and reviews.

Once you have approved the PR, you or any other admin/owner can merge.

Website build and link check tests have passed.

**Comment by Mani-Sadhasivam** [comment]
Just fixed the OV5640 driver inorder to make it work with camss driver. There was no pixel clock support in the upstream driver and camss need it inorder to work.

I will send the patch to Dragonboard ML first since I'm not sure whether this fix is optimal or not!

@ndechesne your views?

**Comment by sdrobertw** [comment]
Pending @ndechesne approval, I think this PR should be merged.

Considering @todortomov is the original contributor of this doc.

**Pull request merged**
