### PR TITLE
developerbox: guides: Add uefi guide to introduce uefi use cases

### PR DESCRIPTION
**Pull request by masahisak**
This pull request is adding uefi boot menu introduction.
Some Developerbox customers send queries how to use uefi boot menu,
this document will help customer as a reference to the uefi.

Signed-off-by: Masahisa Kojima <masahisa.kojima@linaro.org>

### CODE REVIEW

**Comment by sdrobertw** [comment]
@ric96 @Mani-Sadhasivam 
Ignoring link checker

**Comment by masahisak** [comment]
link checker still reports the error.

> 1 failed links have been found:
> /documentation/enterprise/developerbox/guides/index.html:
 >      /documentation/enterprise/developerbox/guides/uefi-guide/index.html

Does this error come from my pull request?
Could you advise how to fix this error?

**Comment by daniel-thompson** [comment]
Firstly my apologies for taking so long to review this. I'm afraid preparing for the debug training webinars is consuming a lot of my time right now.

These instructions are presented in a very different style to other parts of documentation. For example there is instructions on how to enable ACPI in the install documents:
https://github.com/96boards/documentation/blob/5f39e11d02595fe857f6f620e16e45f8ca48f80d/enterprise/developerbox/installation/rhel.md#firmware-set-os-hardware-description-to-acpi .

My gut feeling is if the use cases were more clearly formatted they would not require a screenshot per step (allowing the guides to be shorter) and that would allow us to merge the use-cases already described in the Install from HTTP into a single document perhaps called the "UEFI User Manual".

What are your thoughts on this?

BTW how are the screenshots generated... they seem to have lots of JPEG overcompression artefacts?

**Comment by masahisak** [comment]
Thank you very much for the comments.
We will update to follow the existing format and try to merge.

> BTW how are the screenshots generated... they seem to have lots of JPEG overcompression artefacts?

We  crop the image, then compress it into 400x281 with the following tool(It is Japanese..)
https://forest.watch.impress.co.jp/library/software/shukusen/

**Comment by Mani-Sadhasivam** [comment]
@masahisak Any update on this PR?

**Comment by masahisak** [comment]
Sorry for the late reply.
We are currently preparing menu hierarchy.

**Comment by masahisak** [comment]
I am extremely sorry about super delayed update.

Some customer send query such as:
 - how to enable eMMC?
 - how to add and update boot option?
I would like to add at least these use cases.

**Comment by masahisak** [comment]
Thank you for the comment.
Regarding eMMC in ACPI, I can successfully boot debian 9.8 installed in eMMC with ACPI enabled.
Is there any limitation of using eMMC in ACPI?

**Comment by daniel-thompson** [comment]
> Regarding eMMC in ACPI, I can successfully boot debian 9.8 installed in eMMC with ACPI enabled.
> Is there any limitation of using eMMC in ACPI?

Interesting. Perhaps I'm out of date with some additional upstream patches. Are you using the mainline kernel or the one from Debian 9.8.

Either way, testing trumps theory... and we should probably revert 3dde6d5 .

**Comment by masahisak** [comment]
> Interesting. Perhaps I'm out of date with some additional upstream patches. Are you using the mainline kernel or the one from Debian 9.8.

My kernel is 4.19, this works fine with eMMC in ACPI.
But 4.14(rpk#288) does not work, can not detect eMMC during kernel boot.

**Comment by masahisak** [comment]
Is it ok to revert 3dde6d5?

**Comment by daniel-thompson** [comment]
Sorry @masahisak .

I had tidying this up on my TODO list but I thought this has already been merged so didn't prioritise it. Rather then revert it might be better to mention which kernel ACPI based eMMC was enabled.

Give me a second...

**Comment by daniel-thompson** [comment]
Looks like support landed in v4.15 (same as almost all the reset of Synquacer but it is not backported to the RPK kernel.

On that basis I think you are right, my change is wrong and we should remove (we don't have to revert... just rebase and drop the change).

**Comment by daniel-thompson** [comment]
Would you believe that I made the edits directly (rather than as code review) to try end ensure this landed quickly. Looks like that was an epic fail so sorry about that!

I've removed the patch and pushed again... when the link checkers complete I think I will be able to request a merge.

**Comment by masahisak** [comment]
@daniel-thompson 
Thank you for your quick update.

**Pull request merged**
