### PR TITLE
Migrate links from builds.96boards.org to releases.linaro.org

### PR DESCRIPTION
**Pull request by daniel-thompson**
Fixes: #302

### CODE REVIEW

**Comment by daniel-thompson** [comment]
This is *going* to fail link checking... don't worry about review quite yet.

**Comment by daniel-thompson** [comment]
This is ready for review... I believe all the remaining link check failures are spurious (they are not from the documentation/ directory).

@kylekirkby: are the you the right person to sort out the non-documentation bits and pieces... I don't think these are due to my changes.

**Comment by kylekirkby** [comment]
Hi @daniel-thompson ,

Thanks for this and yes I will sort out the rest of the broken links.

Many Thanks,

**Comment by pcolmer** [comment]
The links to releases are breaking:


/documentation/consumer/dragonboard410c/downloads/open-embedded.md.html:
   http://releases.linaro.org/96boards/reference-platform/openembedded/dragonboard410c/latest/rpb/boot-Image--*-dragonboard-410c-*.img
   http://releases.linaro.org/96boards/reference-platform/openembedded/dragonboard410c/latest/rpb/rpb-desktop-image-dragonboard-410c-*.rootfs.ext4.gz
   http://releases.linaro.org/96boards/reference-platform/openembedded/dragonboard410c/latest/rpb/rpb-console-image-dragonboard-410c-*.rootfs.ext4.gz
   http://releases.linaro.org/96boards/reference-platform/openembedded/dragonboard410c/latest/rpb/
   http://releases.linaro.org/96boards/reference-platform/openembedded/dragonboard410c/latest/rpb-wayland/boot-Image--*-dragonboard-410c-*.img
   http://releases.linaro.org/96boards/reference-platform/openembedded/dragonboard410c/latest/rpb-wayland/rpb-weston-image-dragonboard-410c-*.rootfs.ext4.gz
   http://releases.linaro.org/96boards/reference-platform/openembedded/dragonboard410c/latest/rpb-wayland/rpb-console-image-dragonboard-410c-*.rootfs.ext4.gz
   http://releases.linaro.org/96boards/reference-platform/openembedded/dragonboard410c/latest/rpb-wayland/

@daniel-thompson Are you able to fix these, please? Unfortunately, all 96Boards builds will now stop until they are fixed as I have merged your changes into the repository.

Thanks.

**Comment by sdrobertw** [comment]
@pcolmer @daniel-thompson let me give this a shot.

Will submit PR shortly.

Thanks.

**Comment by fboudra** [comment]
@sdrobertw the old reference-platform have been moved under archive:
http://releases.linaro.org/96boards/archive/reference-platform/

**Comment by sdrobertw** [comment]
I am linking OE builds for DB410 to: https://releases.linaro.org/96boards/dragonboard410c/linaro/openembedded/latest/

**Comment by daniel-thompson** [comment]
On Fri, Mar 02, 2018 at 12:34:53AM -0800, Fathi Boudra wrote:
> @sdrobertw the old reference-platform have been moved under archive:
> http://releases.linaro.org/96boards/archive/reference-platform/

Indeed... that is why the link checks passed this morning but are now
breaking.

**Pull request merged**
